/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Food = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Float64,
  'fiber' : IDL.Float64,
  'carbs' : IDL.Float64,
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'protein' : IDL.Float64,
});
export const MealEntry = IDL.Record({
  'fat' : IDL.Float64,
  'fiber' : IDL.Float64,
  'carbs' : IDL.Float64,
  'date' : IDL.Text,
  'calories' : IDL.Float64,
  'unit' : IDL.Text,
  'entryId' : IDL.Nat,
  'quantity' : IDL.Float64,
  'mealType' : IDL.Text,
  'foodName' : IDL.Text,
  'foodId' : IDL.Nat,
  'protein' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addMealEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addWaterEntry' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'clearEntriesForDate' : IDL.Func([IDL.Text], [], []),
  'getAllFoods' : IDL.Func([], [IDL.Vec(Food)], ['query']),
  'getDailyTotals' : IDL.Func(
      [IDL.Text],
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      ['query'],
    ),
  'getEntriesByMealTypeAndDate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(MealEntry)],
      ['query'],
    ),
  'getEntriesForDate' : IDL.Func([IDL.Text], [IDL.Vec(MealEntry)], ['query']),
  'getFoodById' : IDL.Func([IDL.Nat], [Food], ['query']),
  'getFoodsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Food)], ['query']),
  'getTotalWaterForDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'removeMealEntry' : IDL.Func([IDL.Nat], [], []),
  'removeWaterEntry' : IDL.Func([IDL.Nat], [], []),
  'searchFoods' : IDL.Func([IDL.Text], [IDL.Vec(Food)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Food = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Float64,
    'fiber' : IDL.Float64,
    'carbs' : IDL.Float64,
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const MealEntry = IDL.Record({
    'fat' : IDL.Float64,
    'fiber' : IDL.Float64,
    'carbs' : IDL.Float64,
    'date' : IDL.Text,
    'calories' : IDL.Float64,
    'unit' : IDL.Text,
    'entryId' : IDL.Nat,
    'quantity' : IDL.Float64,
    'mealType' : IDL.Text,
    'foodName' : IDL.Text,
    'foodId' : IDL.Nat,
    'protein' : IDL.Float64,
  });
  
  return IDL.Service({
    'addMealEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addWaterEntry' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'clearEntriesForDate' : IDL.Func([IDL.Text], [], []),
    'getAllFoods' : IDL.Func([], [IDL.Vec(Food)], ['query']),
    'getDailyTotals' : IDL.Func(
        [IDL.Text],
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        ['query'],
      ),
    'getEntriesByMealTypeAndDate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(MealEntry)],
        ['query'],
      ),
    'getEntriesForDate' : IDL.Func([IDL.Text], [IDL.Vec(MealEntry)], ['query']),
    'getFoodById' : IDL.Func([IDL.Nat], [Food], ['query']),
    'getFoodsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Food)], ['query']),
    'getTotalWaterForDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'removeMealEntry' : IDL.Func([IDL.Nat], [], []),
    'removeWaterEntry' : IDL.Func([IDL.Nat], [], []),
    'searchFoods' : IDL.Func([IDL.Text], [IDL.Vec(Food)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };