/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Food {
  'id' : bigint,
  'fat' : number,
  'fiber' : number,
  'carbs' : number,
  'calories' : number,
  'name' : string,
  'category' : string,
  'protein' : number,
}
export interface MealEntry {
  'fat' : number,
  'fiber' : number,
  'carbs' : number,
  'date' : string,
  'calories' : number,
  'unit' : string,
  'entryId' : bigint,
  'quantity' : number,
  'mealType' : string,
  'foodName' : string,
  'foodId' : bigint,
  'protein' : number,
}
export interface _SERVICE {
  'addMealEntry' : ActorMethod<
    [
      bigint,
      string,
      number,
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      string,
    ],
    bigint
  >,
  'addWaterEntry' : ActorMethod<[bigint, string], bigint>,
  'clearEntriesForDate' : ActorMethod<[string], undefined>,
  'getAllFoods' : ActorMethod<[], Array<Food>>,
  'getDailyTotals' : ActorMethod<
    [string],
    [number, number, number, number, number]
  >,
  'getEntriesByMealTypeAndDate' : ActorMethod<
    [string, string],
    Array<MealEntry>
  >,
  'getEntriesForDate' : ActorMethod<[string], Array<MealEntry>>,
  'getFoodById' : ActorMethod<[bigint], Food>,
  'getFoodsByCategory' : ActorMethod<[string], Array<Food>>,
  'getTotalWaterForDate' : ActorMethod<[string], bigint>,
  'removeMealEntry' : ActorMethod<[bigint], undefined>,
  'removeWaterEntry' : ActorMethod<[bigint], undefined>,
  'searchFoods' : ActorMethod<[string], Array<Food>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];