/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Food {
    id: bigint;
    fat: number;
    fiber: number;
    carbs: number;
    calories: number;
    name: string;
    category: string;
    protein: number;
}
export interface MealEntry {
    fat: number;
    fiber: number;
    carbs: number;
    date: string;
    calories: number;
    unit: string;
    entryId: bigint;
    quantity: number;
    mealType: string;
    foodName: string;
    foodId: bigint;
    protein: number;
}
export interface backendInterface {
    addMealEntry(foodId: bigint, foodName: string, quantity: number, unit: string, mealType: string, calories: number, protein: number, carbs: number, fat: number, fiber: number, date: string): Promise<bigint>;
    addWaterEntry(amountMl: bigint, date: string): Promise<bigint>;
    clearEntriesForDate(date: string): Promise<void>;
    getAllFoods(): Promise<Array<Food>>;
    getDailyTotals(date: string): Promise<[number, number, number, number, number]>;
    getEntriesByMealTypeAndDate(mealType: string, date: string): Promise<Array<MealEntry>>;
    getEntriesForDate(date: string): Promise<Array<MealEntry>>;
    getFoodById(id: bigint): Promise<Food>;
    getFoodsByCategory(category: string): Promise<Array<Food>>;
    getTotalWaterForDate(date: string): Promise<bigint>;
    removeMealEntry(entryId: bigint): Promise<void>;
    removeWaterEntry(entryId: bigint): Promise<void>;
    searchFoods(searchText: string): Promise<Array<Food>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMealEntry(arg0: bigint, arg1: string, arg2: number, arg3: string, arg4: string, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMealEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMealEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async addWaterEntry(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWaterEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWaterEntry(arg0, arg1);
            return result;
        }
    }
    async clearEntriesForDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearEntriesForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearEntriesForDate(arg0);
            return result;
        }
    }
    async getAllFoods(): Promise<Array<Food>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoods();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoods();
            return result;
        }
    }
    async getDailyTotals(arg0: string): Promise<[number, number, number, number, number]> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTotals(arg0);
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTotals(arg0);
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4]
            ];
        }
    }
    async getEntriesByMealTypeAndDate(arg0: string, arg1: string): Promise<Array<MealEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesByMealTypeAndDate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesByMealTypeAndDate(arg0, arg1);
            return result;
        }
    }
    async getEntriesForDate(arg0: string): Promise<Array<MealEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntriesForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntriesForDate(arg0);
            return result;
        }
    }
    async getFoodById(arg0: bigint): Promise<Food> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodById(arg0);
            return result;
        }
    }
    async getFoodsByCategory(arg0: string): Promise<Array<Food>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodsByCategory(arg0);
            return result;
        }
    }
    async getTotalWaterForDate(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalWaterForDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalWaterForDate(arg0);
            return result;
        }
    }
    async removeMealEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMealEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMealEntry(arg0);
            return result;
        }
    }
    async removeWaterEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWaterEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWaterEntry(arg0);
            return result;
        }
    }
    async searchFoods(arg0: string): Promise<Array<Food>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFoods(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFoods(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
